const cars = [
{id:"aventador",name:"Lamborghini Aventador",brand:"Lamborghini",country:"Italy",category:"Supercar",year:"2011–2022",engine:"6.5L V12",power:"769 hp",speed:"350 km/h",zero:"2.8 sec",description:"An iconic Italian V12 supercar known for dramatic styling and extraordinary performance.",image:"https://loremflickr.com/1200/700/lamborghini,aventador?lock=1"},
{id:"sf90",name:"Ferrari SF90 Stradale",brand:"Ferrari",country:"Italy",category:"Supercar",year:"2019–Present",engine:"4.0L Twin-Turbo V8 + Hybrid",power:"986 hp",speed:"340 km/h",zero:"2.5 sec",description:"Ferrari's plug-in hybrid flagship combines a twin-turbo V8 with electric motors.",image:"https://loremflickr.com/1200/700/ferrari,sf90?lock=2"},
{id:"chiron",name:"Bugatti Chiron",brand:"Bugatti",country:"France",category:"Hypercar",year:"2016–2024",engine:"8.0L Quad-Turbo W16",power:"1,479 hp",speed:"420 km/h*",zero:"2.4 sec",description:"A celebrated hypercar built around extreme engineering, luxury and speed.",image:"https://loremflickr.com/1200/700/bugatti,chiron?lock=3"},
{id:"porsche911",name:"Porsche 911",brand:"Porsche",country:"Germany",category:"Sports",year:"1964–Present",engine:"Twin-Turbo Flat-Six",power:"Varies by model",speed:"Varies by model",zero:"Varies by model",description:"One of the world's most recognizable sports car families, famous for its rear-engine layout.",image:"https://loremflickr.com/1200/700/porsche,911?lock=4"},
{id:"gtr",name:"Nissan GT-R",brand:"Nissan",country:"Japan",category:"JDM",year:"2007–Present",engine:"3.8L Twin-Turbo V6",power:"Varies by model",speed:"~315 km/h",zero:"~2.5 sec",description:"A Japanese performance icon combining advanced all-wheel drive and twin-turbo power.",image:"https://loremflickr.com/1200/700/nissan,gtr?lock=5"},
{id:"supra",name:"Toyota GR Supra",brand:"Toyota",country:"Japan",category:"JDM",year:"2019–Present",engine:"3.0L Turbo Inline-Six",power:"382 hp*",speed:"250 km/h*",zero:"~4.0 sec",description:"A modern sports car carrying forward the famous Supra name and JDM heritage.",image:"https://loremflickr.com/1200/700/toyota,supra?lock=6"},
{id:"mustang",name:"Ford Mustang",brand:"Ford",country:"USA",category:"Muscle",year:"1964–Present",engine:"Turbocharged / V8 options",power:"Varies by model",speed:"Varies by model",zero:"Varies by model",description:"An American automotive icon that helped define the modern pony-car segment.",image:"https://loremflickr.com/1200/700/ford,mustang?lock=7"},
{id:"amggt",name:"Mercedes-AMG GT",brand:"Mercedes-Benz",country:"Germany",category:"Luxury",year:"2014–Present",engine:"Turbocharged V8",power:"Varies by model",speed:"Varies by model",zero:"Varies by model",description:"A performance-focused grand tourer combining luxury design with strong V8 performance.",image:"https://loremflickr.com/1200/700/mercedes,amg,gt?lock=8"},
{id:"models",name:"Tesla Model S",brand:"Tesla",country:"USA",category:"Electric",year:"2012–Present",engine:"Dual/Triple Electric Motor",power:"Varies by version",speed:"Varies by version",zero:"Varies by version",description:"A well-known electric sedan that helped bring long-range EV performance to a wider audience.",image:"https://loremflickr.com/1200/700/tesla,model-s?lock=9"}
];

const blogs = {
gtr:{category:"Performance",title:"Why the Nissan GT-R Became a JDM Legend",date:"September 2026",art:"🏁",text:["The Nissan GT-R has become one of the best-known names in Japanese performance-car culture. Its combination of technology, all-wheel drive and twin-turbo power helped give the model a distinctive identity.","The GT-R's popularity also grew through motorsport, enthusiast communities and popular media. Generations of fans have made the car an important part of JDM culture.","Rather than being famous for one specification alone, the GT-R story is about engineering, evolution and a long-running connection with enthusiasts around the world."]},
ev:{category:"Technology",title:"How Electric Cars Are Changing the Automotive World",date:"September 2026",art:"⚡",text:["Electric vehicles are changing the automobile through electric motors, battery technology and software. Electric motors can deliver torque very quickly, creating a different driving experience from conventional engines.","Modern EVs also depend heavily on software. Vehicle controls, displays, charging systems and driver-assistance features can be updated and improved over time.","The automotive industry continues to develop battery technology, charging infrastructure and new vehicle platforms as electric mobility expands."]},
hyper:{category:"Guide",title:"Supercar vs Hypercar — What's the Difference?",date:"September 2026",art:"🏎️",text:["The terms supercar and hypercar are often used to describe high-performance vehicles, but they are not strict engineering standards. Manufacturers and automotive media may use them differently.","Supercars generally represent an especially high level of performance, technology and design. Hypercars are usually positioned at an even more exclusive level, often using extreme engineering, advanced materials or hybrid systems.","The most useful way to understand the categories is to look at the vehicle's performance, technology, production numbers, price positioning and purpose rather than relying on one single definition."]}
};